name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v1
      - run: ls -l
      - run: yarn install
      - run: yarn build-all

      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
